const cartTypes = {
    GET_CART_ITEMS: 'GET_CART_ITEMS',
    ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
    REMOVE_ITEM_FROM_CART: 'REMOVE_FROM_CART',
    DECREMENT_ITEM_FROM_CART: 'DECREMENT_ITEM_FROM_CART',
    EMPTY_ITEMS_FROM_CART: 'EMPTY_ITEMS_FROM_CART'
}

export default cartTypes