const productTypes = {
    FETCH_COFEE_PRODUCTS: 'FETCH_COFEE_PRODUCTS',
    FETCH_TEA_PRODUCTS: 'FETCH_TEA_PRODUCTS',
    SEARCH_COFFE_PRODUCTS: 'SEARCH_COFFE_PRODUCTS',
    SEARCH_TEA_PRODUCTS: 'SEARCH_TEA_PRODUCTS',
    FETCH_PRODUCT: 'FETCH_PRODUCT',
    RESET_PRODUCT: 'RESET_PRODUCT'
}

export default productTypes